[build-system]
requires = ["setuptools >= 40.9.0",]
build-backend = "setuptools.build_meta"

[owner]
name = "Panchdev Singh Chauhan"

authors = [{ name = "Panchdev Chauhan", email = "erpanchdev@gmail.com" }]

[project]
name = "nrobo"
description = "An Automated Testing Framework For Web Testing By NamasteyDigitalIndia.com"
readme = "README.rst"
version = "2024.1.3"
keywords = ["test automation", "test automation framework", "automated testing", "automation testing", "testing", "qa", "acceptance test", "automation"]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing :: Acceptance",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Unit",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "License :: Freeware",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Information Technology",
    "Framework :: Pytest"
]
requires-python = ">=3.8"
#license = "MIT"
#include = ["CHANGELOG.rst"]

dependencies = []

[project.optional-dependencies]
dev = []


[project.urls]
"Homepage" = "https://pypi.org/project/nrobo/"
"Bug Tracker" = "https://github.com/pancht/nrobodocs/issues"
"changelog" = "https://github.com/pancht/nrobodocs/blob/master/CHANGELOG.md"

[project.scripts]
nrobo = "nrobo:launch_nRoBo"


#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"
#
#[tool.hatch.build]
#include = [
#  "nrobo-copy/*.*", "nrobo-copy/**","nrobo-copy/**/*.*", "nrobo-copy/**/**", "nrobo-copy/**/**/*.*"
#]

#[build-system]
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "tests_api",
    "tests_performance"
]

#[tool.hatch.build.targets.wheel]
#packages = ["nrobo-copy"]
#
#[tool.hatch.build.targets.sdist]
#include = [
#  "nrobo-copy"
#]

[tool.setuptools.packages.find]
where = ["."]
include = ["nrobo*",]
#            "nrobo-copy/**",
#            "nrobo-copy/**/*.*",
#            "nrobo-copy/assets/chartjs/**",
#            "nrobo-copy/assets/chartjs/**/*.*",
#            "nrobo-copy/assets/chartjs/*.*",
#            "nrobo-copy/tests_advanced_reports*"]  # alternatively: `exclude = ["additional*"]`
namespaces = true

[tool.setuptools.package-data]
"*" = ["*.*"]